### ISSUE TITLE
Flow 0.68.0 compatibility

### ISSUE THREAD

**Issue by stevehollaar** [graphql/graphql-js#1291]
Flow 0.68 added some changes that introduce some new errors:

```
$> yarn flow
yarn run v1.5.1
$ /Users/stevehollaar/graphql-js/node_modules/.bin/flow
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/error/locatedError.js:25:38

Property path is missing in Error [1].

 [1] 19│   originalError: Error,
     20│   nodes: $ReadOnlyArray<ASTNode>,
     21│   path: $ReadOnlyArray<string | number>,
     22│ ): GraphQLError {
     23│   // Note: this uses a brand-check to support GraphQL errors originating from
     24│   // other contexts.
     25│   if (originalError && Array.isArray(originalError.path)) {
     26│     return (originalError: any);
     27│   }
     28│


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/subscription/mapAsyncIterator.js:25:14

Property return is missing in $AsyncIterator [1].

     src/subscription/mapAsyncIterator.js
      22│   const iterator = getAsyncIterator(iterable);
      23│   let $return;
      24│   let abruptClose;
      25│   if (typeof iterator.return === 'function') {
      26│     $return = iterator.return;
      27│     abruptClose = error => {
      28│       const rethrow = () => Promise.reject(error);

     node_modules/iterall/index.js.flow
 [1] 506│   & (<+TValue>(asyncIterable: AsyncIterable<TValue>) => AsyncIterator<TValue>)


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/subscription/mapAsyncIterator.js:59:18

Property throw is missing in $AsyncIterator [1].

     src/subscription/mapAsyncIterator.js
      56│         : Promise.resolve({ value: undefined, done: true });
      57│     },
      58│     throw(error) {
      59│       if (typeof iterator.throw === 'function') {
      60│         return iterator.throw(error).then(mapResult, mapReject);
      61│       }
      62│       return Promise.reject(error).catch(abruptClose);

     node_modules/iterall/index.js.flow
 [1] 506│   & (<+TValue>(asyncIterable: AsyncIterable<TValue>) => AsyncIterator<TValue>)



Found 3 errors
```

**Comment by IvanGoncharov** [comment]
@stevehollaar It should be fixed by #1290

**Comment by kassens** [comment]
I just published 0.13.2 with #1290 merged which should fix this.

**Comment by protodaniel** [comment]
@stevehollaar, was this fixed for you? 
I think it's still broken. Tried with both flow 0.68.0 and 0.69.0

**Comment by stevehollaar** [comment]
@protodaniel Yes - upgrading to `graphql-js: 0.13.2` fixed this for me (using `flow-bin: 0.69.0` right now)

**Comment by protodaniel** [comment]
I see, for some reason I was missing this line in the [options] of my .flowconfig
suppress_comment= \\(.\\|\n\\)*\\$FlowFixMe

I also saw that the fix is just to tell Flow to shut up ;)

Thanks for the help!
