### ISSUE TITLE
Regression: Importing the package fails in a brand new Vite project

### ISSUE THREAD

**Issue by srmagura** [graphql/graphql-js#3918]
Minimal repro: https://github.com/srmagura/graphql-repro

The project was created with:

```shell
npm create-vite@latest graphql-repro
```

Then I chose "Vanilla" and "TypeScript" at the prompts.

Install the `graphql` npm package and add the import

```ts
import * as graphql from "graphql";
```

It produces an error like:

```ts
Uncaught SyntaxError: Unexpected string (at graphql.js?v=4b27e75c:1248:113)
```

If you click on the error in the console, you'll see that `process.env.NODE_ENV` has been replaced with "development".

![image](https://github.com/graphql/graphql-js/assets/801549/e588221f-afbc-4e1c-a6c8-97587e2ae828)

Let me know if you think this is a Vite issue instead, and I will report it there.

**Comment by airhorns** [comment]
This got us too -- I think the regexp here is not working quite right: https://github.com/sun0day/vite/blob/5c6c0d381755cf7bd46854937e7dd3e2aea323f3/packages/vite/src/node/plugins/clientInjections.ts#L68-L72

**Comment by bburr** [comment]
Just adding more info - the `$` in `_globalThis$process` seen here is what's not accounted for in the regexp - https://diff.intrinsic.com/graphql/16.6.0/16.7.0#file-jsutils__instanceOf.mjs

So `_globalThis$process.env.NODE_ENV` gets changed to `_globalThis$"development"` by Vite

**Comment by IvanGoncharov** [comment]
@srmagura It's an issue with Vite internals, but I added a workaround for it in `16.7.1`
Can you please confirm that it is fixed?

**Comment by KangMiSun17** [comment]
@IvanGoncharov I was having the same problem and it was solved. Thank you.

**Comment by LrMiLoef** [comment]
i still have the problem, using the `16.7.1` and vite `2.9.16`.  
when i undo your fix, it's working.

**Comment by lemonmade** [comment]
@IvanGoncharov I believe that the issue is still present, even with your change applied:

<img width="1185" alt="Screenshot 2023-06-23 at 2 46 14 PM" src="https://github.com/graphql/graphql-js/assets/3012583/ee6763d5-7d41-4026-8fef-e3652b791675">

I believe a more common way of checking whether you are in Node is to do `typeof process === 'object'`, like this: https://github.com/graphql/graphql-js/compare/16.x.x...lemonmade:graphql-js:fix-process-env-replacement?expand=1. `@rollup/plugin-replace`, which is also affected by this issue, actually has special handling for this code pattern: https://github.com/rollup/plugins/tree/master/packages/replace#objectguards.

**Comment by B2o5T** [comment]
Why this happens I wrote in https://github.com/graphql/graphql-js/issues/3925

**Comment by phryneas** [comment]
@lemonmade did you change the default configuration of `@rollup/plugin-replace`?

According to the documentation on the [delimiters option](https://github.com/rollup/plugins/tree/master/packages/replace#delimiters), the default value for that option should guard against deep property access.

Or are you using another bundler and only also mention that rollup plugin?

`typeof process` is problematic, as some other bundlers are not able to replace that at all, as it is a full statement, not just a variable name/access.

**Comment by salcedo** [comment]
Error still present on Quasar Framework with Vite

```
 » Dev mode............... spa
 » Pkg quasar............. v2.12.0
 » Pkg @quasar/app-vite... v1.4.3
```

```
├─┬ @quasar/app-vite@1.4.3
│ ├─┬ @quasar/vite-plugin@1.4.0
│ │ ├── @vitejs/plugin-vue@2.3.4 deduped
│ │ ├── vite@2.9.16 deduped
```

**Comment by NGPixel** [comment]
Same problem here with Quasar + Vite with graphql@16.7.1

**Comment by davidsims9t** [comment]
I tried rolling back to 16.6.0 and I'm still having the same issue with Vite.

**Comment by phryneas** [comment]
@davidsims9t in that case, maybe clear your vite cache?

**Comment by jptaranto** [comment]
Hitting this using Rollup as well as we're replacing the `NODE_ENV` key for React production builds as per this ancient technique: https://github.com/rollup/rollup/issues/208

The fix for me in this case was to add another replace option for graphql in `rollup.config.js`:

```
replace({
  "globalThis.process.env.NODE_ENV": JSON.stringify(process.env.NODE_ENV),
  "process.env.NODE_ENV": JSON.stringify(process.env.NODE_ENV),
  preventAssignment: true,
}),
```

**Comment by romanpastu** [comment]
I had to downgrade all the way down to 15.6.1 for it to work, for me it failed in graphql 16.6.0 with vite , suddenly out of nowhere while i was developing. After that I have not been bale to do anything to restore it, and I ended up having to test previous version, settled at 15.6.1

**Comment by unckleg** [comment]
Any updates?

**Comment by JoviDeCroock** [comment]
I hope to be merging https://github.com/graphql/graphql-js/pull/4022 after the next WG which should remove these issues... We have investigated more in https://github.com/graphql/graphql-js/issues/4075

**Comment by JoviDeCroock** [comment]
This is fixed in https://github.com/graphql/graphql-js/pull/4022 and published in GraphQL 16.8.2, you can find the instructions for various bundlers [here](https://github.com/graphql/graphql-js/blob/16.x.x/website/docs/tutorials/going-to-production.md) on how to remove it in production.
