### ISSUE TITLE
Parsing error was not very useful

### ISSUE THREAD

**Issue by jay-at-avido** [graphql/graphql-js#798]
Hi, 

I got the error below, which lookes to me like graphql was trying to output a useful parsing error but failed to do so. 
After a lot of trial and error I eventually narrowed it down to being a mutation declaration that did not specify any parameters

`/Users/joao/node_projects/my-server/node_modules/graphql/error/syntaxError.js:28
  var error = new _GraphQLError.GraphQLError('Syntax Error ' + source.name + ' (' + location.line + ':' + location.column + ') ' + description + '\n\n' + highlightSourceAtLocation(source, location), undefined, source, [position]);
              ^
GraphQLError
    at syntaxError (/Users/joao/node_projects/my-server/node_modules/graphql/error/syntaxError.js:28:15)
    at expect (/Users/joao/node_projects/my-server/node_modules/graphql/language/parser.js:966:32)
    at parseName (/Users/joao/node_projects/my-server/node_modules/graphql/language/parser.js:88:15)
    at parseInputValueDef (/Users/joao/node_projects/my-server/node_modules/graphql/language/parser.js:743:14)
    at many (/Users/joao/node_projects/my-server/node_modules/graphql/language/parser.js:1015:16)
    at parseArgumentDefs (/Users/joao/node_projects/my-server/node_modules/graphql/language/parser.js:735:10)
    at parseFieldDefinition (/Users/joao/node_projects/my-server/node_modules/graphql/language/parser.js:714:14)
    at any (/Users/joao/node_projects/my-server/node_modules/graphql/language/parser.js:1002:16)
    at parseObjectTypeDefinition (/Users/joao/node_projects/my-server/node_modules/graphql/language/parser.js:683:16)
    at parseTypeSystemDefinition (/Users/joao/node_projects/my-server/node_modules/graphql/language/parser.js:607:16)`

I wonder if this could be improved somehow to provide a better debugging experience, thanks!

**Comment by wincent** [comment]
That is indeed not very useful. How were you invoking the parser to obtain this output?

**Comment by jay-at-avido** [comment]
Thanks for responding.
I was running a Node (FeathersJS) server.

**Comment by leebyron** [comment]
Should be fixed by #718

**Comment by jay-at-avido** [comment]
I'm still getting a lot of similar if not the same error: 
`
/Users/joao/node_projects/proto-server/node_modules/graphql/error/syntaxError.js:28
  var error = new _GraphQLError.GraphQLError('Syntax Error ' + source.name + ' (' + location.line + ':' + location.column + ') ' + description + '\n\n' + highlightSourceAtLocation(source, location), undefined, source, [position]);

GraphQLError
    at syntaxError (/Users/joao/node_projects/proto-server/node_modules/graphql/error/syntaxError.js:28:15)
    at expect (/Users/joao/node_projects/proto-server/node_modules/graphql/language/parser.js:966:32)
    at any (/Users/joao/node_projects/proto-server/node_modules/graphql/language/parser.js:999:3)
    at parseInputObjectTypeDefinition (/Users/joao/node_projects/proto-server/node_modules/graphql/language/parser.js:854:16)
    at parseTypeSystemDefinition (/Users/joao/node_projects/proto-server/node_modules/graphql/language/parser.js:615:16)
    at parseDefinition (/Users/joao/node_projects/proto-server/node_modules/graphql/language/parser.js:148:16)
    at parseDocument (/Users/joao/node_projects/proto-server/node_modules/graphql/language/parser.js:106:22)
    at Object.parse (/Users/joao/node_projects/proto-server/node_modules/graphql/language/parser.js:43:10)
    at buildSchemaFromTypeDefinitions (/Users/joao/node_projects/proto-server/node_modules/graphql-tools/src/schemaGenerator.ts:145:37)
    at _generateSchema (/Users/joao/node_projects/proto-server/node_modules/graphql-tools/src/schemaGenerator.ts:72:18)
`
Not sure what repo this is coming from.  graphl-tools ?
